### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by sivelswhy** [Wamy-Dev/ReziWebsite#13]
First, add an option on the website to report broken links,
Second, this link is broken : https://gamesdrive.net/Thread-Emergency-Call-112-The-Fire-Fighting-Simulation-2-SKIDROW
![image](https://github.com/Wamy-Dev/ReziWebsite/assets/82051273/3b842f84-30e3-46b9-aad6-fd0b2e6b8dbd)

**Comment by Wamy-Dev** [comment]
Thanks for that, I'll look into a report page or button (probably a page to make it easier on myself, and a filter for items being scraped.

**Comment by Wamy-Dev** [comment]
Links can now be requested to be removed. Was too lazy to put it on the site as that would require it's own API which I don't have, and would be pointless to make for one feature. Maybe if I get some time in the future, I will look into doing it properly. 

For future reference if anyone wants to report a dead link they can do one of the following
- Message me personally on Discord to report it
- Open a support ticket on my Discord server about it
- Make an issue about it in this GitHub repo
- Create a pull request editing the `deadlinks.json` file, which the scraper reads off of to make sure it doesn't submit a link that is in that list.

It's a good enough solution for now considering that there probably wont be too many dead links anyways.
