### ISSUE TITLE
Add filters

### ISSUE THREAD

**Issue by ggtylerr** [Wamy-Dev/ReziWebsite#19]
When you search for a game that's multi-platform (and/or have different region versions) it gives you a bunch of different results you may not want. Adding a filter system (i.e. selecting what console it's on) would fix this problem.

**Comment by Wamy-Dev** [comment]
If you want to search by console, you can use search modifiers, (kinda), if I want to download "Mario 64" for the Nintendo 64, I would type, "N64 Mario 64" and the results that come first will be for Nintendo 64. Same with any other console. You can also search for just the console, such as typing in "Gameboy" and it will only show gameboy results.
