### ISSUE TITLE
[BUG] Searching does not work

### ISSUE THREAD

**Issue by ggtylerr** [Wamy-Dev/ReziWebsite#2]
**Describe the bug**
Searching simply brings up a ton of errors - A lot of them seeming like it's CORS related, although the CORS everywhere addon does not fix the issue.
[Error log](https://paste.fmhy.cf/626242289)

**To Reproduce**
1. Literally just attempt a search

**Expected behavior**
Search results

**Screenshots**
![firefox_YfvD0TMP1C](https://user-images.githubusercontent.com/28498877/193378525-fadd7d89-06a5-4aa7-8e90-2ff1ae71abbf.png)
The same thing happens on chromium.

**Severity/Priority**
10

**Additional Notes**
Attempted on both laptop (Ungoogled Chromium + FF nightly) and mobile (Iceraven.) No VPN and with Mullvad. No addons and with CORS everywhere.

**Comment by Wamy-Dev** [comment]
Fixed. Recently reconfigured my server and got the ports mixed up.  Sorry!
