### ISSUE TITLE
[Quirk] Empty search results on loading website

### ISSUE THREAD

**Issue by megz15** [Wamy-Dev/ReziWebsite#5]
Not an annoying bug or anything, but when you first load the website it shows "No results have been found for ." for a second

![nvwXCRY](https://user-images.githubusercontent.com/56220472/200756308-8c7f9ff3-c1e9-4309-82d9-2bc01b6c4122.png)

**Comment by Wamy-Dev** [comment]
Honestly been meaning to fix it, spent a couple minutes doing it. Bam
