### ISSUE TITLE
The actual total page count is not displayed correctly

### ISSUE THREAD

**Issue by lratan** [Wamy-Dev/ReziWebsite#7]
Hello, 
When I did a search on a game, first it shows me that it was only 2 pages available and I thought that all the games I searched for wasn't available.

![image](https://user-images.githubusercontent.com/33748881/212038466-5635dbac-4a71-445c-8cdb-474f29200004.png)

But then when I went to the next page, the number of available pages just increased. 

![image](https://user-images.githubusercontent.com/33748881/212038551-f98f354f-2676-48d9-8076-b2ad484cac95.png)

I know it's a feature from Meilisearch to avoid to iterate on all the db, but imo for UX it's a bad experience.

Regards,

**Comment by irevoire** [comment]
![image](https://user-images.githubusercontent.com/7032172/212040603-b2026ce6-4342-4003-8efa-2ab9782595fa.png)
From what I see, you're asking _a lot_ of results to Meili (141), you could use that number to display a minimum number of pages.

Or, the other fast solution is to cheat like google and use the `estimatedTotalHits` to compute a « fake » number of pages (the closer you get to the end, the more precise it’ll get).

And the third solution I can think of is displaying [`1`, `2`, `...`] so you don’t engage on anything and the users understand that there is more pages left

**Comment by Wamy-Dev** [comment]
Interesting, never thought of it as a problem, Ill take a look. And yeah I just realized that I am asking a lot of meili, (141) which is like page 30 or something, and by that time, thats a lot.

**Comment by Wamy-Dev** [comment]
I did some tinkering and a lot of reading... getting that state to my custom pagination component using Instantsearch and MaterialUI is just not possible the way I have it right now. It would mean completely replacing and upgrading to react hooks. Idk the effort doesn't seem worth it. There are those arrows at the end which wouldn't be there if there were no other items. I can do more digging though.

Ill leave some literature but I only get so much for that component from Meilisearch.

https://www.algolia.com/doc/api-reference/widgets/pagination/react/
https://mui.com/material-ui/react-pagination/

**Comment by Wamy-Dev** [comment]
Material UI does have a very customizable pagination component, its just that I literally get no data from meilisearch/instantsearch for it to mean anything.

**Comment by Wamy-Dev** [comment]
Decided to take another shot at this, and I actually fixed the issue. Moved a little code around so I have access to the esitmatedTotalHits and now simply I divide by 5 to get the total number of pages. Still haven't fix the page 41 issue though so you can't actually get to page 200, so maybe I'll fix it.

![Screenshot from 2023-06-18 21-37-23](https://github.com/Wamy-Dev/ReziWebsite/assets/25761442/c9184bd0-1bcf-4ca3-a506-ef5a28c208ff)
