### ISSUE TITLE
Blood Trail

### ISSUE THREAD

**Issue by devilofeggs** [Wamy-Dev/ReziWebsite#8]
https://store.steampowered.com/app/1032430/Blood_Trail/

Would love to see this by anyone other than IGG.

Thanks what what yall do

**Comment by Wamy-Dev** [comment]
Rezi does not host or crack any of the games, it just provides links to them. IGG Games is not a trusted source and you definitely shouldn't download from them. We don't have any links from them on Rezi. 

It doesnt seem like Blood Trail is a cracked game either which means that nobody has it anywhere. Don't download it from anywhere as it would be fake.
